*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: /ILSIEDU/VDMRM..................................*
FORM GET_DATA_/ILSIEDU/VDMRM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /ILSIEDU/DMRM WHERE
(VIM_WHERETAB) .
    CLEAR /ILSIEDU/VDMRM .
/ILSIEDU/VDMRM-RUNMODE =
/ILSIEDU/DMRM-RUNMODE .
/ILSIEDU/VDMRM-CLASS =
/ILSIEDU/DMRM-CLASS .
/ILSIEDU/VDMRM-DYNNR =
/ILSIEDU/DMRM-DYNNR .
/ILSIEDU/VDMRM-ACTIVE =
/ILSIEDU/DMRM-ACTIVE .
    SELECT SINGLE * FROM /ILSIEDU/DMRMT WHERE
RUNMODE = /ILSIEDU/DMRM-RUNMODE AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ILSIEDU/VDMRM-TEXT =
/ILSIEDU/DMRMT-TEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = /ILSIEDU/VDMRM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/ILSIEDU/VDMRM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /ILSIEDU/VDMRM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/ILSIEDU/VDMRM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /ILSIEDU/DMRM WHERE
  RUNMODE = /ILSIEDU/VDMRM-RUNMODE .
    IF SY-SUBRC = 0.
    DELETE /ILSIEDU/DMRM .
    ENDIF.
    DELETE FROM /ILSIEDU/DMRMT WHERE
    RUNMODE = /ILSIEDU/DMRM-RUNMODE .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /ILSIEDU/DMRM WHERE
  RUNMODE = /ILSIEDU/VDMRM-RUNMODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /ILSIEDU/DMRM.
    ENDIF.
/ILSIEDU/DMRM-RUNMODE =
/ILSIEDU/VDMRM-RUNMODE .
/ILSIEDU/DMRM-CLASS =
/ILSIEDU/VDMRM-CLASS .
/ILSIEDU/DMRM-DYNNR =
/ILSIEDU/VDMRM-DYNNR .
/ILSIEDU/DMRM-ACTIVE =
/ILSIEDU/VDMRM-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE /ILSIEDU/DMRM ##WARN_OK.
    ELSE.
    INSERT /ILSIEDU/DMRM .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM /ILSIEDU/DMRMT WHERE
    RUNMODE = /ILSIEDU/DMRM-RUNMODE AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR /ILSIEDU/DMRMT.
/ILSIEDU/DMRMT-RUNMODE =
/ILSIEDU/DMRM-RUNMODE .
/ILSIEDU/DMRMT-SPRAS =
SY-LANGU .
      ENDIF.
/ILSIEDU/DMRMT-TEXT =
/ILSIEDU/VDMRM-TEXT .
    IF SY-SUBRC = 0.
    UPDATE /ILSIEDU/DMRMT ##WARN_OK.
    ELSE.
    INSERT /ILSIEDU/DMRMT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/ILSIEDU/VDMRM-UPD_FLAG,
STATUS_/ILSIEDU/VDMRM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/ILSIEDU/VDMRM.
  SELECT SINGLE * FROM /ILSIEDU/DMRM WHERE
RUNMODE = /ILSIEDU/VDMRM-RUNMODE .
/ILSIEDU/VDMRM-RUNMODE =
/ILSIEDU/DMRM-RUNMODE .
/ILSIEDU/VDMRM-CLASS =
/ILSIEDU/DMRM-CLASS .
/ILSIEDU/VDMRM-DYNNR =
/ILSIEDU/DMRM-DYNNR .
/ILSIEDU/VDMRM-ACTIVE =
/ILSIEDU/DMRM-ACTIVE .
    SELECT SINGLE * FROM /ILSIEDU/DMRMT WHERE
RUNMODE = /ILSIEDU/DMRM-RUNMODE AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
/ILSIEDU/VDMRM-TEXT =
/ILSIEDU/DMRMT-TEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR /ILSIEDU/VDMRM-TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/ILSIEDU/VDMRM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /ILSIEDU/VDMRM-RUNMODE TO
/ILSIEDU/DMRM-RUNMODE .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ILSIEDU/DMRM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ILSIEDU/DMRM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ILSIEDU/DMRM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE /ILSIEDU/DMRM-RUNMODE TO
/ILSIEDU/DMRMT-RUNMODE .
MOVE SY-LANGU TO
/ILSIEDU/DMRMT-SPRAS .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/ILSIEDU/DMRMT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /ILSIEDU/DMRMT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/ILSIEDU/DMRMT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
